/**
 * Document Node Executor
 *
 * Generates document content based on input data.
 *
 * Requirement 3.5: WHEN executing a document node, THE Node_Executor SHALL
 * generate the document content based on input data.
 */

import { BaseNodeExecutor } from './base-executor.js';
import type { NodeExecutionParams, NodeExecutionResult } from './types.js';
import type { CanvasNodeType } from '../../types/workflow-execution.js';
import { aiService } from '../ai.service.js';

/**
 * Document node metadata structure
 */
interface DocumentNodeMeta {
  /** Processing status */
  status?: string;
  /** Template for document generation */
  template?: string;
  /** Document format */
  format?: 'markdown' | 'html' | 'text' | 'json';
  /** Whether to use AI for generation */
  useAI?: boolean;
  /** AI prompt for generation */
  aiPrompt?: string;
  /** Share ID for public access */
  shareId?: string;
  /** Parent result ID (if generated by agent) */
  parentResultId?: string;
}

/**
 * Document node executor
 *
 * Generates documents using:
 * - Template-based generation with variable substitution
 * - AI-powered content generation
 * - Direct content pass-through
 */
export class DocumentNodeExecutor extends BaseNodeExecutor {
  readonly supportedTypes: CanvasNodeType[] = ['document'];

  async execute(params: NodeExecutionParams): Promise<NodeExecutionResult> {
    const { node, context } = params;
    const metadata = this.getMetadata<DocumentNodeMeta>(params);

    try {
      let content: string;

      if (metadata?.useAI && metadata?.aiPrompt) {
        // AI-powered document generation
        content = await this.generateWithAI(params, metadata);
      } else if (metadata?.template) {
        // Template-based generation
        content = this.generateFromTemplate(params, metadata);
      } else {
        // Use content preview or generate from parent outputs
        content = this.generateFromContext(params);
      }

      // Format the content if needed
      const formattedContent = this.formatContent(content, metadata?.format);

      return this.success({
        type: 'document',
        title: node.data.title,
        format: metadata?.format || 'markdown',
        content: formattedContent,
        result: formattedContent,
        characterCount: formattedContent.length,
        wordCount: formattedContent.split(/\s+/).filter(Boolean).length,
        timestamp: new Date().toISOString(),
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      const errorStack = error instanceof Error ? error.stack : undefined;

      console.error(`Document node execution failed: ${errorMessage}`, {
        nodeId: node.id,
        executionId: context.executionId,
        error,
      });

      return this.failure(
        `Document generation failed: ${errorMessage}`,
        errorStack
      );
    }
  }

  /**
   * Generate document content using AI
   */
  private async generateWithAI(
    params: NodeExecutionParams,
    metadata: DocumentNodeMeta
  ): Promise<string> {
    const { context } = params;

    // Build prompt with context
    let prompt = this.substituteVariables(metadata.aiPrompt || '', context);

    // Add parent outputs as context
    const parentContext = this.buildParentContext(context);
    if (parentContext) {
      prompt = `Context:\n${parentContext}\n\n${prompt}`;
    }

    // Generate using AI service
    const response = await aiService.chatCompletion({
      system_prompt:
        'You are a professional document writer. Generate clear, well-structured content based on the provided context and instructions.',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 4096,
    });

    return response;
  }

  /**
   * Generate document from template
   */
  private generateFromTemplate(
    params: NodeExecutionParams,
    metadata: DocumentNodeMeta
  ): string {
    const { context } = params;
    const template = metadata.template || '';

    // Substitute variables in template
    return this.substituteVariables(template, context);
  }

  /**
   * Generate document from context (parent outputs)
   */
  private generateFromContext(params: NodeExecutionParams): string {
    const { node, context } = params;

    // Use content preview if available
    if (node.data.contentPreview) {
      return this.substituteVariables(node.data.contentPreview, context);
    }

    // Build document from parent outputs
    const sections: string[] = [];

    // Add title
    sections.push(`# ${node.data.title}\n`);

    // Add parent outputs as sections
    context.nodeOutputs.forEach((output, nodeId) => {
      // Skip pass-through outputs
      if (
        typeof output === 'object' &&
        output !== null &&
        'passThrough' in output
      ) {
        return;
      }

      const outputStr =
        typeof output === 'string'
          ? output
          : JSON.stringify(output, null, 2);

      // Extract title if available
      const title =
        typeof output === 'object' && output !== null && 'title' in output
          ? String((output as Record<string, unknown>).title)
          : `Section from ${nodeId}`;

      sections.push(`## ${title}\n\n${outputStr}\n`);
    });

    return sections.join('\n');
  }

  /**
   * Build context string from parent outputs
   */
  private buildParentContext(context: NodeExecutionParams['context']): string {
    const parts: string[] = [];

    context.nodeOutputs.forEach((output, nodeId) => {
      // Skip pass-through outputs
      if (
        typeof output === 'object' &&
        output !== null &&
        'passThrough' in output
      ) {
        return;
      }

      const outputStr =
        typeof output === 'string'
          ? output
          : JSON.stringify(output, null, 2);

      parts.push(`--- ${nodeId} ---\n${outputStr}`);
    });

    return parts.join('\n\n');
  }

  /**
   * Format content based on specified format
   */
  private formatContent(
    content: string,
    format?: 'markdown' | 'html' | 'text' | 'json'
  ): string {
    switch (format) {
      case 'html':
        return this.markdownToHtml(content);

      case 'text':
        return this.stripMarkdown(content);

      case 'json':
        // Try to parse as JSON, otherwise wrap in object
        try {
          JSON.parse(content);
          return content;
        } catch {
          return JSON.stringify({ content }, null, 2);
        }

      case 'markdown':
      default:
        return content;
    }
  }

  /**
   * Simple markdown to HTML conversion
   */
  private markdownToHtml(markdown: string): string {
    let html = markdown;

    // Headers
    html = html.replace(/^### (.*$)/gm, '<h3>$1</h3>');
    html = html.replace(/^## (.*$)/gm, '<h2>$1</h2>');
    html = html.replace(/^# (.*$)/gm, '<h1>$1</h1>');

    // Bold and italic
    html = html.replace(/\*\*\*(.*?)\*\*\*/g, '<strong><em>$1</em></strong>');
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

    // Code blocks
    html = html.replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code class="$1">$2</code></pre>');
    html = html.replace(/`(.*?)`/g, '<code>$1</code>');

    // Links
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');

    // Line breaks
    html = html.replace(/\n\n/g, '</p><p>');
    html = `<p>${html}</p>`;

    return html;
  }

  /**
   * Strip markdown formatting
   */
  private stripMarkdown(markdown: string): string {
    let text = markdown;

    // Remove headers
    text = text.replace(/^#{1,6}\s+/gm, '');

    // Remove bold/italic
    text = text.replace(/\*\*\*(.*?)\*\*\*/g, '$1');
    text = text.replace(/\*\*(.*?)\*\*/g, '$1');
    text = text.replace(/\*(.*?)\*/g, '$1');

    // Remove code blocks
    text = text.replace(/```[\s\S]*?```/g, '');
    text = text.replace(/`(.*?)`/g, '$1');

    // Remove links, keep text
    text = text.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');

    return text.trim();
  }
}
