/**
 * Node Metadata Types - Type-specific metadata for each canvas node type
 * 
 * Each node type has its own metadata structure that extends the base CanvasNodeData.
 */

import type { ActionStatus, CodeArtifactType } from './node-types';

// Re-define minimal types here to avoid circular dependency
// (../index re-exports ./canvas which includes this file)
interface AgentRef {
  id: string;
  name: string;
  role: string;
  avatar: string;
  systemPrompt: string;
}

interface ToolRef {
  id: string;
  name: string;
  skillMd: string;
}

interface ModelConfigRef {
  provider: 'Bedrock' | 'OpenAI' | 'Azure';
  modelId: string;
  agentType: 'Orchestrator' | 'Worker' | 'Supervisor';
}

// ============================================================================
// Agent Node Metadata
// ============================================================================

/**
 * Metadata for agent nodes - your core Agent concept
 */
export interface AgentNodeMeta {
  /** Reference to the agent definition */
  agentId?: string;
  /** Agent configuration snapshot */
  agent?: Pick<AgentRef, 'id' | 'name' | 'role' | 'avatar' | 'systemPrompt'>;
  /** Query/prompt for this execution */
  query?: string;
  /** Result ID from execution */
  resultId?: string;
  /** Execution version */
  version?: number;
  /** Model configuration */
  modelConfig?: ModelConfigRef;
  /** Selected tools for this execution */
  selectedTools?: ToolRef[];
  /** Context items (references to other nodes) */
  contextItems?: ContextItem[];
  /** Execution status */
  status?: ActionStatus;
  /** Token usage */
  tokenUsage?: TokenUsageItem[];
  /** Errors if any */
  errors?: string[];
  /** Size mode for display */
  sizeMode?: 'compact' | 'adaptive';
  /** Custom styles */
  style?: React.CSSProperties;
  /** Original width before resize */
  originalWidth?: number;
}

/**
 * Context item - reference to another node or resource
 */
export interface ContextItem {
  type: 'agent' | 'document' | 'resource' | 'codeArtifact';
  entityId: string;
  title?: string;
  metadata?: {
    withHistory?: boolean;
    [key: string]: unknown;
  };
}

/**
 * Token usage tracking
 */
export interface TokenUsageItem {
  modelName: string;
  modelProvider: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
}

// ============================================================================
// Document Node Metadata
// ============================================================================

/**
 * Metadata for document nodes - rich text output
 */
export interface DocumentNodeMeta {
  /** Processing status */
  status: ActionStatus;
  /** Size mode */
  sizeMode?: 'compact' | 'adaptive';
  /** Custom styles */
  style?: React.CSSProperties;
  /** Original width */
  originalWidth?: number;
  /** Share ID for public access */
  shareId?: string;
  /** Parent result ID (if generated by agent) */
  parentResultId?: string;
}

// ============================================================================
// Code Artifact Node Metadata
// ============================================================================

/**
 * Metadata for code artifact nodes
 */
export interface CodeArtifactNodeMeta {
  /** Generation status */
  status?: 'generating' | 'finish' | 'failed' | 'executing';
  /** Share ID */
  shareId?: string;
  /** Preview URL */
  previewUrl?: string;
  /** Programming language */
  language?: string;
  /** Artifact type */
  type?: CodeArtifactType;
  /** Artifact title */
  title?: string;
  /** Size mode */
  sizeMode?: 'compact' | 'adaptive';
  /** Custom styles */
  style?: React.CSSProperties;
  /** Original width */
  originalWidth?: number;
  /** Active tab in viewer */
  activeTab?: 'code' | 'preview';
  /** Parent result ID */
  parentResultId?: string;
}

// ============================================================================
// Resource Node Metadata
// ============================================================================

/**
 * Resource types
 */
export type ResourceType = 
  | 'weblink'
  | 'text'
  | 'file'
  | 'document'
  | 'image'
  | 'video'
  | 'audio';

/**
 * Resource metadata
 */
export interface ResourceMeta {
  url?: string;
  title?: string;
  contentType?: string;
}

/**
 * Index status for resources
 */
export type IndexStatus = 'pending' | 'processing' | 'completed' | 'failed';

/**
 * Metadata for resource nodes
 */
export interface ResourceNodeMeta {
  /** Resource type */
  resourceType?: ResourceType;
  /** Resource metadata */
  resourceMeta?: ResourceMeta;
  /** Indexing status */
  indexStatus?: IndexStatus;
  /** Index error if any */
  indexError?: {
    type?: 'pageLimitExceeded' | 'unknownError';
    metadata?: Record<string, unknown>;
  };
  /** Size mode */
  sizeMode?: 'compact' | 'adaptive';
  /** Custom styles */
  style?: React.CSSProperties;
  /** Original width */
  originalWidth?: number;
  /** Share ID */
  shareId?: string;
}

// ============================================================================
// Human Approval Node Metadata
// ============================================================================

/**
 * Approval status
 */
export type ApprovalStatus = 'pending' | 'approved' | 'rejected' | 'timeout';

/**
 * Metadata for human approval nodes
 */
export interface HumanApprovalNodeMeta {
  /** Approval status */
  status: ApprovalStatus;
  /** Approver user ID */
  approverId?: string;
  /** Approver name */
  approverName?: string;
  /** Approval timestamp */
  approvedAt?: string;
  /** Rejection reason */
  rejectionReason?: string;
  /** Timeout duration in seconds */
  timeoutSeconds?: number;
  /** Instructions for approver */
  instructions?: string;
  /** Size mode */
  sizeMode?: 'compact' | 'adaptive';
  /** Custom styles */
  style?: React.CSSProperties;
}

// ============================================================================
// Trigger Node Metadata
// ============================================================================

/**
 * Trigger types
 */
export type TriggerType = 
  | 'manual'      // User-initiated
  | 'schedule'    // Cron-based
  | 'webhook'     // HTTP webhook
  | 'event';      // System event

/**
 * Metadata for trigger nodes
 */
export interface TriggerNodeMeta {
  /** Trigger type */
  triggerType: TriggerType;
  /** Cron expression (for schedule) */
  cronExpression?: string;
  /** Webhook URL (for webhook) */
  webhookUrl?: string;
  /** Event name (for event) */
  eventName?: string;
  /** Last triggered timestamp */
  lastTriggeredAt?: string;
  /** Size mode */
  sizeMode?: 'compact' | 'adaptive';
  /** Custom styles */
  style?: React.CSSProperties;
}

// ============================================================================
// Action Node Metadata
// ============================================================================

/**
 * Action types
 */
export type ActionType = 
  | 'api_call'
  | 'database'
  | 'notification'
  | 'transform'
  | 'custom';

/**
 * Metadata for action nodes
 */
export interface ActionNodeMeta {
  /** Action type */
  actionType: ActionType;
  /** Action configuration */
  config?: Record<string, unknown>;
  /** Execution status */
  status?: ActionStatus;
  /** Result data */
  result?: unknown;
  /** Error message */
  error?: string;
  /** Size mode */
  sizeMode?: 'compact' | 'adaptive';
  /** Custom styles */
  style?: React.CSSProperties;
}

// ============================================================================
// Condition Node Metadata
// ============================================================================

/**
 * Condition operator
 */
export type ConditionOperator = 
  | 'equals'
  | 'not_equals'
  | 'contains'
  | 'not_contains'
  | 'greater_than'
  | 'less_than'
  | 'is_empty'
  | 'is_not_empty'
  | 'custom';

/**
 * Condition rule
 */
export interface ConditionRule {
  field: string;
  operator: ConditionOperator;
  value?: unknown;
  customExpression?: string;
}

/**
 * Metadata for condition nodes
 */
export interface ConditionNodeMeta {
  /** Condition rules */
  rules: ConditionRule[];
  /** Logic operator between rules */
  logic: 'and' | 'or';
  /** Evaluation result */
  result?: boolean;
  /** Size mode */
  sizeMode?: 'compact' | 'adaptive';
  /** Custom styles */
  style?: React.CSSProperties;
}

// ============================================================================
// Start/End Node Metadata
// ============================================================================

/**
 * Metadata for start nodes
 */
export interface StartNodeMeta {
  /** Input variables */
  inputVariables?: WorkflowVariableDefinition[];
  /** Size mode */
  sizeMode?: 'compact' | 'adaptive';
  /** Custom styles */
  style?: React.CSSProperties;
}

/**
 * Metadata for end nodes
 */
export interface EndNodeMeta {
  /** Output mapping */
  outputMapping?: Record<string, string>;
  /** Final status */
  status?: 'success' | 'failure';
  /** Size mode */
  sizeMode?: 'compact' | 'adaptive';
  /** Custom styles */
  style?: React.CSSProperties;
}

// ============================================================================
// Workflow Variable Types
// ============================================================================

/**
 * Variable value types
 */
export type VariableValueType = 'text' | 'resource';

/**
 * Variable resource type
 */
export type VariableResourceType = 'document' | 'image' | 'video' | 'audio';

/**
 * Resource value for variables
 */
export interface ResourceValue {
  name: string;
  fileType: VariableResourceType;
  fileId?: string;
  storageKey?: string;
  entityId?: string;
}

/**
 * Variable value
 */
export interface VariableValue {
  type: VariableValueType;
  text?: string;
  resource?: ResourceValue;
}

/**
 * Workflow variable definition
 */
export interface WorkflowVariableDefinition {
  variableId: string;
  name: string;
  value: VariableValue[];
  description?: string;
  variableType?: 'string' | 'option' | 'resource';
  required?: boolean;
  isSingle?: boolean;
  options?: string[];
  resourceTypes?: VariableResourceType[];
  createdAt?: string;
  updatedAt?: string;
}

// ============================================================================
// Metadata Type Map
// ============================================================================

/**
 * Type mapping for node metadata by node type
 */
export interface NodeMetadataMap {
  agent: AgentNodeMeta;
  document: DocumentNodeMeta;
  codeArtifact: CodeArtifactNodeMeta;
  resource: ResourceNodeMeta;
  humanApproval: HumanApprovalNodeMeta;
  start: StartNodeMeta;
  trigger: TriggerNodeMeta;
  action: ActionNodeMeta;
  condition: ConditionNodeMeta;
  end: EndNodeMeta;
  loop: Record<string, unknown>;
  parallel: Record<string, unknown>;
  group: Record<string, unknown>;
  memo: Record<string, unknown>;
}
