-- Rehearsal Sessions: tracks automated agent evaluation sessions
-- triggered by accumulated scope memories (gaps, lessons).

CREATE TABLE "rehearsal_sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "business_scope_id" UUID NOT NULL,
    "agent_id" UUID,
    "rehearsal_type" VARCHAR(50) NOT NULL DEFAULT 'memory_triggered',
    "trigger_memory_ids" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "agent_config_snapshot" JSONB NOT NULL DEFAULT '{}',
    "scenario" JSONB NOT NULL DEFAULT '{}',
    "evaluation" JSONB,
    "status" VARCHAR(20) NOT NULL DEFAULT 'pending',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "completed_at" TIMESTAMPTZ,

    CONSTRAINT "rehearsal_sessions_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "rehearsal_sessions_organization_id_fkey"
        FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE,
    CONSTRAINT "rehearsal_sessions_business_scope_id_fkey"
        FOREIGN KEY ("business_scope_id") REFERENCES "business_scopes"("id") ON DELETE CASCADE
);

CREATE INDEX "rehearsal_sessions_organization_id_idx" ON "rehearsal_sessions"("organization_id");
CREATE INDEX "rehearsal_sessions_business_scope_id_idx" ON "rehearsal_sessions"("business_scope_id");
CREATE INDEX "rehearsal_sessions_status_idx" ON "rehearsal_sessions"("status");
CREATE INDEX "rehearsal_sessions_created_at_idx" ON "rehearsal_sessions"("created_at" DESC);

-- Scope Evolution Proposals: change proposals generated by rehearsal evaluations.

CREATE TABLE "scope_evolution_proposals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "business_scope_id" UUID NOT NULL,
    "rehearsal_session_id" UUID,
    "trigger_memory_ids" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "proposal_type" VARCHAR(50) NOT NULL,
    "proposed_changes" JSONB NOT NULL DEFAULT '[]',
    "evaluation_score" INTEGER,
    "evaluation_summary" TEXT,
    "status" VARCHAR(20) NOT NULL DEFAULT 'pending',
    "reviewed_by" UUID,
    "review_note" TEXT,
    "applied_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "scope_evolution_proposals_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "scope_evolution_proposals_organization_id_fkey"
        FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE,
    CONSTRAINT "scope_evolution_proposals_business_scope_id_fkey"
        FOREIGN KEY ("business_scope_id") REFERENCES "business_scopes"("id") ON DELETE CASCADE,
    CONSTRAINT "scope_evolution_proposals_rehearsal_session_id_fkey"
        FOREIGN KEY ("rehearsal_session_id") REFERENCES "rehearsal_sessions"("id") ON DELETE SET NULL
);

CREATE INDEX "scope_evolution_proposals_organization_id_idx" ON "scope_evolution_proposals"("organization_id");
CREATE INDEX "scope_evolution_proposals_business_scope_id_idx" ON "scope_evolution_proposals"("business_scope_id");
CREATE INDEX "scope_evolution_proposals_status_idx" ON "scope_evolution_proposals"("status");
CREATE INDEX "scope_evolution_proposals_created_at_idx" ON "scope_evolution_proposals"("created_at" DESC);
